version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - rabbitmq_network

    linha_producao_container:
        build:
            context: /home/lucca/desktop/distribuids/Trabalho-SDistribuidos-Docker/Downloads/SistemasDistribuidos-t2-main/linha_producao
            dockerfile: Dockerfile
        networks:
            - rabbitmq_network
        depends_on:
            - rabbitmq

    fabrica_container:
        build:
            context: /home/lucca/desktop/distribuids/Trabalho-SDistribuidos-Docker/Downloads/SistemasDistribuidos-t2-main/fabrica
            dockerfile: Dockerfile
        networks:
            - rabbitmq_network
        depends_on:
            - rabbitmq

    fornecedor_container:
        build:
            context: /home/lucca/desktop/distribuids/Trabalho-SDistribuidos-Docker/Downloads/SistemasDistribuidos-t2-main/fornecedor
            dockerfile: Dockerfile_fornecedor
        networks:
            - rabbitmq_network
        depends_on:
            - rabbitmq

    almoxarifado_container:
        build:
            context: /home/lucca/desktop/distribuids/Trabalho-SDistribuidos-Docker/Downloads/SistemasDistribuidos-t2-main/Almoxarifado
            dockerfile: Dockerfile
        networks:
            - rabbitmq_network
        depends_on:
            - rabbitmq

    produto_container:
        build:
            context: /home/lucca/desktop/distribuids/Trabalho-SDistribuidos-Docker/Downloads/SistemasDistribuidos-t2-main/produto
            dockerfile: Dockerfile
        networks:
            - rabbitmq_network
        depends_on:
            - rabbitmq

volumes:
    rabbitmq_data:

networks:
    rabbitmq_network:
        name: rabbitmq_network
        driver: bridge
