version: '3.8'

services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
        networks:
            - rabbitmq_network

    linha_producao_container:
        build:
            context: C:\mosquitto\linha_producao
            dockerfile: Dockerfile
        networks:
            - rabbitmq_network

    fabrica_container:
        build:
            context: C:\mosquitto\fabrica
            dockerfile: Dockerfile
        networks:
            - rabbitmq_network

    fornecedor_container:
        build:
            context: C:\mosquitto\fornecedor
            dockerfile: Dockerfile_fornecedor
        networks:
            - rabbitmq_network

    almoxarifado_container:
        build:
            context: C:\mosquitto\Almoxarifado
            dockerfile: Dockerfile
        networks:
            - rabbitmq_network

    produto_container:
        build:
            context: C:\mosquitto\produto
            dockerfile: Dockerfile
        networks:
            - rabbitmq_network

volumes:
    rabbitmq_data:

networks:
    rabbitmq_network:
        name: rabbitmq_network
        driver: bridge